from _base import VisionDataset
from _sun09 import SUN09
from _sun397 import SUN397
from _indoor09 import Indoor09
from _lfwcropped import LFWcrop
from _caltech256 import Caltech256
from _msrc import MSRC
from _voc07 import VOC07
from _esp import ESP
from _fifteen_scene import FifteenScene
from _attribute import Attribute
from _cifar10 import CIFAR10
from _cifar100 import CIFAR100
